/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout.index'
import { Route as LayoutSearchSearchImport } from './routes/_layout.search/$search'
import { Route as LayoutPhotoIdImport } from './routes/_layout.photo/$id'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchSearchRoute = LayoutSearchSearchImport.update({
  id: '/search/$search',
  path: '/search/$search',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPhotoIdRoute = LayoutPhotoIdImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/photo/$id': {
      id: '/_layout/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof LayoutPhotoIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/$search': {
      id: '/_layout/search/$search'
      path: '/search/$search'
      fullPath: '/search/$search'
      preLoaderRoute: typeof LayoutSearchSearchImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutPhotoIdRoute: typeof LayoutPhotoIdRoute
  LayoutSearchSearchRoute: typeof LayoutSearchSearchRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutPhotoIdRoute: LayoutPhotoIdRoute,
  LayoutSearchSearchRoute: LayoutSearchSearchRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/photo/$id': typeof LayoutPhotoIdRoute
  '/search/$search': typeof LayoutSearchSearchRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/photo/$id': typeof LayoutPhotoIdRoute
  '/search/$search': typeof LayoutSearchSearchRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/photo/$id': typeof LayoutPhotoIdRoute
  '/_layout/search/$search': typeof LayoutSearchSearchRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/photo/$id' | '/search/$search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/photo/$id' | '/search/$search'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/photo/$id'
    | '/_layout/search/$search'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/photo/$id",
        "/_layout/search/$search"
      ]
    },
    "/_layout/": {
      "filePath": "_layout.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/photo/$id": {
      "filePath": "_layout.photo/$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/search/$search": {
      "filePath": "_layout.search/$search.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
